# Generated by Django 2.0.5 on 2018-05-03 04:57

from django.db import migrations, models
import django.db.models.deletion
import orders.utils.Utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(max_length=15)),
                ('ord_file', models.FileField(upload_to=orders.utils.Utils.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=15, unique=True)),
                ('lang', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('direction', models.CharField(max_length=20)),
                ('urgency', models.CharField(default='2', max_length=10)),
                ('customer', models.CharField(max_length=15)),
                ('file_path', models.CharField(default='orders_files/<django.db.models.fields.CharField>', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Status'),
        ),
    ]
