# Generated by Django 2.0.5 on 2018-05-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='translated',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='translator.Translator'),
        ),
    ]
