# Generated by Django 2.0.5 on 2018-05-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('reg_date', models.CharField(max_length=20)),
                ('busy', models.CharField(default='0', max_length=5)),
                ('direction', models.ManyToManyField(to='orders.Direction')),
            ],
        ),
    ]
